ansible_user: cyberrange
ansible_password: "Cyberrange123!"
ansible_connection: winrm
ansible_winrm_transport: basic
ansible_winrm_port: 5985
ansible_winrm_scheme: http
ansible_winrm_server_cert_validation: ignore

ad_domain: "scp.local"
ad_domain_netbios: "SCP"
ad_domain_controller_ip: "10.10.10.21"
ad_safe_mode_password: "SafeMode!Restore99"
